project:
  type: website

execute:
  freeze: auto

website:
  title: "Michal Mottl"
  site-url: "https://mottl.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Work with me
      - href: about.qmd
        text: About
      - posts.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



